### PR TITLE
 Run cppcheck on a temporary file with a possibly unsaved document text

### LINKED ISSUE #14: cppcheck errors/warnings not cleared when source file updated
### Environment

* Operating System (e.g. Ubuntu 16.04 x64): 
 CentOS Linux release 7.3.1611 (Core)

* IDE Version (e.g. CLion 2016.3.2):
CLion 2017.3.3 

* Cppcheck executable version (`cppcheck --version`): 
Cppcheck 1.80

* Cppcheck plugin version:
1.0.10

* Exact strings used in cppcheck plugin options:
  * **cppcheck path**:
/usr/bin/cppcheck

  * **cppcheck options**: 
--enable=warning,performance,portability,style --inline-suppr --suppress=unusedStructMember --suppress=variableScope --suppress=uninitvar --language=c

### Expected behaviour
If a warning/error that was reported by cppcheck is fixed then I would expect that the current file would be updated and the warning/error would be removed (i.e., the underline would be removed)

### Actual behaviour
The error remains on the original line number.  If the error was fixed without adding/removing any lines then the error remains on that same line.  If lines are added or removed the error still points to the old line number even though that line has nothing to do with the error being reported.

I find that I have to edit the cppcheck plugin configuration and save/apply them in order to get the file to be re-analyzed again.  Just editing the file is not enough.

### Steps to reproduce the behaviour
1. edit a file and introduce an error that cppcheck will find (in my case that was a "redundantAssignment" style error).  
2. wait for analysis to complete and observe that a warning is now present
3. fix the error
4. wait for analysis to complete and observer that the warning is still present even though it was fixed.

### PR DESCRIPTION
**Pull request by fastasturtle**
Here is the PR that hopefully fixes #14. Before the cppcheck is run, a temp file with the document contents is created, and the header search path with the original directory is prepended to mimic the normal behavior.

Unfortunately, I've had to move some things around to do it, so the diff is rather unnecessary noisy.

### CODE REVIEW

File: src/com/github/johnthagen/cppcheck/CppcheckInspection.java [hunk 1]
```diff
@@ -37,122 +42,135 @@
...
+    return ProblemDescriptor.EMPTY_ARRAY;
+  }
+
+  @NotNull
+  private static String prependIncludeDir(@NotNull String cppcheckOptions, @NotNull VirtualFile vFile) {
+    VirtualFile dir = vFile.getParent();
+    if (dir == null) return cppcheckOptions;
+    String path = dir.getCanonicalPath();
+    if (path == null) return cppcheckOptions;
+    return String.format("-I\"%s\" %s", path, cppcheckOptions);
```
Comment (johnthagen) [inline src/com/github/johnthagen/cppcheck/CppcheckInspection.java]: What happens if the user provides their own `-I` options? Will this conflict? If so, do we need to at least add a mention about that in the configuration window to warn users?

**Comment by johnthagen** [comment]
Wow, the plugin runs **so** much better with these changes!

File: src/com/github/johnthagen/cppcheck/CppcheckInspection.java [hunk 2]
```diff
@@ -37,122 +42,135 @@
...
+        severityToHighlightType(severity),
+        true);
+      descriptors.add(problemDescriptor);
+    }
+    return descriptors;
   }
 
   private static final int TIMEOUT_MS = 60 * 1000;
 
   private static String executeCommandOnFile(final String command,
```
[the remark this answers is not in the document]
Comment (fastasturtle) [reply src/com/github/johnthagen/cppcheck/CppcheckInspection.java]: Yes, they should, I probably wasn't too consistent with (not) adding them

File: src/com/github/johnthagen/cppcheck/CppcheckInspection.java (hunk 1 above)
Comment (fastasturtle) [reply src/com/github/johnthagen/cppcheck/CppcheckInspection.java]: If I read cppcheck docs correctly, multiple `-I`s are allowed, and they are searched in the order they appear (so that's why I'm adding it in front: current dir always takes precedence in the header search path).

Btw, it lacks `""` vs` <>` differentiation, so now `<>`-path could be found relative to the original file's directory. I don't know if it's possible to fix without changing the cppcheck itself, and I think the benefits outweigh the possible problems.
